#!/usr/bin/env python
# -*- coding: utf-8 -*-

from django.db.models import signals
from tf.core.Customer.models import Customer
from tf.core.Customer import models as customer_app

def post_customer_syncdb(app, created_models, verbosity, **kwargs):
    if Customer in created_models:
        pass


signals.post_syncdb.connect(post_customer_syncdb, sender=customer_app)
